version: "3.8"

services:
  db:
    container_name: my_words_db_container
    image: postgres
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    ports:
      - "${SQL_PORT}:5432"
    networks:
      - db
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    container_name: my_words_app_container
    image: my_words_app_container
    env_file: .env.compose
    ports:
      - "8000:8000"
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  pgdata:
