version: '3.8'

services:
  db:
    container_name: my_words_db_container
    image: postgres
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    ports:
      - '${SQL_PORT}:5432'
    networks:
      - db

networks:
  db:
    driver: bridge
