version: '3.8'

services:
  db:
    container_name: my_words_db_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5492:5432'
    networks:
      - db

networks:
  db:
    driver: bridge
