# Generated by Django 4.2.7 on 2023-12-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worddefinition',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
