# Generated by Django 4.2.7 on 2023-11-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_quiz_quizquestion_quizquestionproposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddefinition',
            name='example',
            field=models.TextField(null=True),
        ),
    ]
