# Generated by Django 4.2.7 on 2023-12-13 11:53

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_quiz_nbr_right_answers_alter_worddefinition_example_and_more'),
    ]

    operations = [
        UnaccentExtension()
    ]
