# Generated by Django 4.2.7 on 2023-12-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_auto_20231213_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('GUESS_FROM_DEFINITION', 'GUESS_FROM_DEFINITION'), ('GUESS_FROM_WORD', 'GUESS_FROM_WORD')], default='GUESS_FROM_DEFINITION'),
            preserve_default=False,
        ),
    ]
