# Generated by Django 4.2.7 on 2023-11-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_worddefinition_user_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='worddefinition',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
