# Generated by Django 4.2.7 on 2023-12-26 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_collection_worddefinition_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='index',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
