# Generated by Django 4.2.7 on 2023-11-30 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_quiz_user_alter_quizquestion_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestionproposal',
            name='index',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
