# Generated by Django 4.2.7 on 2023-12-26 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_collection_index'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='worddefinition',
            name='user_slug_unique',
        ),
        migrations.AlterField(
            model_name='worddefinition',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='definitions', to='words.collection'),
        ),
        migrations.AddConstraint(
            model_name='worddefinition',
            constraint=models.UniqueConstraint(fields=('user', 'slug', 'collection_id'), name='user_slug_unique'),
        ),
    ]
