# Generated by Django 4.2.7 on 2023-11-30 10:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_quizquestionproposal_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='index',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
