# Generated by Django 4.2.7 on 2023-11-30 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_quizquestion_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='response_index',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
