# Generated by Django 4.2.7 on 2023-11-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_quizquestion_response_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'NOT_STARTED'), ('PARTIALLY_COMPLETE', 'PARTIALLY_COMPLETE'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED'),
        ),
    ]
