# Generated by Django 4.2.7 on 2024-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_wordtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='tags',
            field=models.ManyToManyField(related_name='quizes', to='words.wordtag'),
        ),
    ]
