# Generated by Django 4.2.7 on 2023-11-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='nbr_proposals',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='quiz',
            name='nbr_questions',
            field=models.IntegerField(default=10),
        ),
    ]
